---
- include: etc_hosts.yml

- hosts: ansiblesetup
  become: true
  vars:
    use_bundle: true
    postgres_streaming_replication: false
    ansible_tower_version: 3.2.3-1.el7
  pre_tasks:
    - yum: name=vim-enhanced
  roles:
    - role: geerlingguy.repo-epel
    - role: setup-tower
    - role: network-routes
    - role: fetch-ssh-key
    - role: install-tower-cli
